### ISSUE TITLE
Quick instructional

### ISSUE THREAD

**Issue by sc4ryb3ar** [ameygat/githuballrepo#1]
Will you please add instructions for use in your readme? I am familiar with Java and Android, and am a custom ROM dev, so the code looks familiar, and I could probably bumble through it; But it would be nice for me, and for noobs to be able to replace and execute quickly.

**Comment by ameygat** [comment]
As written in the Readme Description:
  These are python scripts to download all git repositories of a user or
organisation.

If you execute the script it would have also shown the usage:

  git_allrepo_org.py name_of_the_organisation

The script will download all git repository of that organization.

**Comment by sc4ryb3ar** [comment]
Oh, sorry, I misunderstood, I thought that you had to change something in the script....Yay easy! Thank you kindly :)
