### ISSUE TITLE
Only gets public repos

### ISSUE THREAD

**Issue by pastephens** [ameygat/githuballrepo#4]
If Requests can authenticate, the script could find all repos the user has access to, and then download them all.

**Comment by ameygat** [comment]
https://github.com/ameygat/githuballrepo/commit/36e6c45f230ea382a2f92a23b92e2134c46998d6

Added API Key to API call but still searching option to provide API key in bash git clone command.

**Comment by pastephens** [comment]
Auth should take place within a session object, right?

**Comment by pastephens** [comment]
http://docs.python-requests.org/en/master/user/advanced/#session-objects

**Comment by ameygat** [comment]
> http://docs.python-requests.org/en/master/user/advanced/#session-objects On Fri, Nov 30, 2018 at 10:36 AM Philip Stephens <phil.stphns@gmail.com> wrote:
> […](#)
> Auth should take place within a session object, right? 

This API call also works if send key in call, its not secure but dirty patch.
You are welcome to send a pull request, I would not be getting time till at-least couple of weeks.
